dist: bionic

language: ruby
rvm:
 - 2.6.3

branches:
  only:
  - master
  - eager-loading

script:
  - yarn install
  - bundle exec rake db:migrate
  - APPMAP=true bundle exec rake test
  - jq '[.events[] | select(has("sql_query"))] | length' tmp/appmap/minitest/Microposts_interface_micropost_interface.appmap.json
