---
openapi: 3.0.1
info:
  title: Rails Sample App API
  version: v6
paths:
  "/microposts":
    get:
      summary: lists current user microposts
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
    post:
      summary: creates a micropost
      responses:
        '302':
          description: not logged in
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
