---
openapi: 3.0.1
info:
  title: Rails Sample App 6th Edition API
  version: v6
paths:
  "/microposts":
    post:
      summary: creates a micropost
      responses:
        '302':
          description: not logged in
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
