---
openapi: 3.0.1
info:
  title: Rails Sample App API
  version: v6
components:
  securitySchemes:
    session_cookie:
      type: session_id
      in: cookie
      name: _sample_app_session

security:
  - session_cookie: []
paths:
  "/":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/about":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/account_activations/{id}/edit":
    get:
      description: ''
      responses:
        '302':
          content: {}
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/contact":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/help":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/login":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
    post:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: session
        in: query
        schema:
          type: object
  "/logout":
    delete:
      description: ''
      responses:
        '302':
          content: {}
  "/microposts":
    get:
      description: ''
      responses:
        '200':
          content:
            application/json: {}
    post:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: micropost
        in: query
        schema:
          type: object
  "/microposts/{id}":
    delete:
      description: ''
      responses:
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/password_resets":
    post:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: password_reset
        in: query
        schema:
          type: string
  "/password_resets/new":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/password_resets/{id}":
    patch:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: user
        in: query
        schema:
          type: object
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/password_resets/{id}/edit":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/relationships":
    post:
      description: ''
      responses:
        '200':
          content:
            text/javascript: {}
        '302':
          content:
            text/html: {}
      parameters:
      - name: followed_id
        in: query
        schema:
          type: string
  "/relationships/{id}":
    delete:
      description: ''
      responses:
        '200':
          content:
            text/javascript: {}
        '302':
          content:
            text/html: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/signup":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
  "/users":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
    post:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: user
        in: query
        schema:
          type: object
  "/users/{id}":
    delete:
      description: ''
      responses:
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    patch:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: user
        in: query
        schema:
          type: object
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/edit":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/followers":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/following":
    get:
      description: ''
      responses:
        '200':
          content:
            text/html: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
