---
openapi: 3.0.1
info:
  title: Rails Sample App API
  version: v6
paths:
  "/":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: home
  "/about":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: about
  "/account_activations/{id}/edit":
    get:
      responses:
        '302':
          content: {}
          description: Found
      description: Activate the account of an existing user.
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/contact":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: contact
  "/help":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: help
  "/login":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: new
    post:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: Login a new user.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/session.yaml"
  "/logout":
    delete:
      responses:
        '302':
          content: {}
          description: Found
      description: destroy
  "/microposts":
    get:
      responses:
        '200':
          content:
            application/json: {}
          description: OK
      description: index
    post:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/micropost.yaml"
  "/microposts/{id}":
    delete:
      responses:
        '302':
          content: {}
          description: Found
        '303':
          content: {}
          description: See Other
      description: destroy
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/password_resets":
    post:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/password_reset.yaml"
  "/password_resets/new":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: new
  "/password_resets/{id}":
    patch:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: update
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/email.yaml"
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/password_resets/{id}/edit":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: edit
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/relationships":
    post:
      responses:
        '200':
          content:
            text/javascript: {}
          description: OK
        '302':
          content:
            text/html: {}
          description: Found
      description: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/followed_id.yaml"
  "/relationships/{id}":
    delete:
      responses:
        '200':
          content:
            text/javascript: {}
          description: OK
        '302':
          content:
            text/html: {}
          description: Found
      description: destroy
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/signup":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: new
  "/users":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: index
    post:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/user.yaml"
  "/users/{id}":
    delete:
      responses:
        '302':
          content: {}
          description: Found
      description: destroy
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
      description: show
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    patch:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: update
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "./schema/user.yaml"
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/edit":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: edit
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/followers":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: followers
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
  "/users/{id}/following":
    get:
      responses:
        '200':
          content:
            text/html: {}
          description: OK
        '302':
          content: {}
          description: Found
      description: following
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
